AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pre-sign-up

  Sample SAM Template for pre-sign-up
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ExergenPreSignUpFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: pre-sign-up/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        PreSignUp:
          Type: Api
          Properties:
            Path: /pre-sign-up
            Method: post
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ExergenPreSignUpFunction:
    Description: "ExergenPreSignUp Lambda Function ARN"
    Value: !GetAtt ExergenPreSignUpFunction.Arn
  ExergenPreSignUpFunctionIamRole:
    Description: "Implicit IAM Role created for ExergenPreSignUp function"
    Value: !GetAtt ExergenPreSignUpFunctionRole.Arn
